Repository wordpress-mobile/release-toolkit, pull requests merged in 2020-07, with the labels that each got.

#145 Merge release 0.9.10 back into develop
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#146 Release/0.9.10
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_build_prechecks.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/metadata_download_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#147 Don't update Android release_notes_short if the source file is empty
  lib/fastlane/plugin/wpmreleasetoolkit/helper/an_metadata_update_helper.rb
Labels: bug

#149 Release/0.9.11
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/helper/an_metadata_update_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#148 Merge Release/0.9.11 back into develop
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#142 Fix: typos in fastlane's close_milestone_action description
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/close_milestone_action.rb
Labels: bug

#152 Tracking multiple localizations
  lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
  spec/promo_screenshots_helper_spec.rb
Labels: enhancement

#153 Release/0.9.12
  .circleci/config.yml
  Gemfile.lock
  docs/screenshot-compositor.md
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/close_milestone_action.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
  spec/promo_screenshots_helper_spec.rb
Labels: Releases
