Repository wordpress-mobile/release-toolkit, pull requests merged in 2021-12, with the labels that each got.

#313 Add support for commenting on GitHub PRs
  .rubocop_todo.yml
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/comment_on_pr.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/github_helper.rb
  spec/github_helper_spec.rb
Labels: Releases

#318 Fixes broken GitHub helper
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/helper/github_helper.rb
  spec/github_helper_spec.rb
Labels: bug

#320 Add GitHub Client Memoization Test
  spec/github_helper_spec.rb
Labels: enhancement

#322 Release 2.2.0 into trunk
  .rubocop_todo.yml
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/comment_on_pr.rb
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/create_release_action.rb
  lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_generate_strings_file_from_code.rb
  lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_localize_project.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/github_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
  spec/github_helper_spec.rb
  spec/ios_generate_strings_file_from_code_spec.rb
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-custom-routine/AppStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-custom-routine/Localizable.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-custom-routine/PodStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-nopods-noswiftui/AppStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-nopods-noswiftui/Localizable.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-nopods-swiftui/AppStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-nopods-swiftui/Localizable.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-pods-noswiftui/AppStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-pods-noswiftui/Localizable.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-pods-noswiftui/PodStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-pods-swiftui/AppStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-pods-swiftui/Localizable.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/expected-pods-swiftui/PodStrings.strings
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Pods/SomePod/README.md
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Pods/SomePod/Sources/PodClass1.swift
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Pods/SomePod/Sources/PodClass2.h
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Pods/SomePod/Sources/PodClass2.m
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Pods/SomePod/Sources/PodSampleView.swift
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Sources/AppClass1.swift
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Sources/AppClass2.h
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Sources/AppClass2.m
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Sources/AppSampleView.swift
  spec/test-data/translations/ios_generate_strings_file_from_code/sample-project/Sources/Doc.md
Labels: Releases

#323 Release 2.2.0 into develop
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#324 Release 2.3.0 into trunk
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases
