Repository wordpress-mobile/release-toolkit, pull requests merged in 2021-07, with the labels that each got.

#285 Release/1.3.1
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_betabuild_prechecks.rb
  lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_build_prechecks.rb
  lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_finalize_prechecks.rb
  lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_tag_build.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_version_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/glotpress_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
  spec/android_version_helper_spec.rb
  spec/check_localization_progress_spec.rb
Labels: Releases

#286 Merge Release/1.3.1 into develop
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#282 Update dependencies
  CHANGELOG.md
  Gemfile.lock
  fastlane-plugin-wpmreleasetoolkit.gemspec
Labels: enhancement

#276 Fix a bug in the `plugin_root` method
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/helper/filesystem_helper.rb
Labels: bug
