Repository wordpress-mobile/release-toolkit, pull requests merged in 2022-08, with the labels that each got.

#391 Fixes milestones being compared as strings
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/helper/github_helper.rb
  spec/github_helper_spec.rb
Labels: bug

#392 Add the ability for the `buildkite_trigger_build` action to provide a custom message
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/buildkite_trigger_build_action.rb
Labels: enhancement

#393 Release 5.2.0 into trunk
  .bundle/config
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#402 Add an option to retry when GlotPress download fails on "429 Too Many Requests" errors
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_localize_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_l10n_helper.rb
  spec/ios_download_strings_files_from_glotpress_spec.rb
  spec/ios_l10n_helper_spec.rb
Labels: enhancement

#404 Release 5.4.0
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases
