Repository wordpress-mobile/release-toolkit, pull requests merged in 2022-03, with the labels that each got.

#339 Add Upload to S3 Action
  .rubocop_todo.yml
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/upload_to_s3.rb
  spec/spec_helper.rb
  spec/upload_to_s3_spec.rb
Labels: enhancement

#343 Update `Gemfile.lock` (via `bundle install`) after 3.1.0 release
  Gemfile.lock
Labels: bug

#347 Bumped to version 4.0.0
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#341 Update Dependencies
  CHANGELOG.md
  Gemfile.lock
  fastlane-plugin-wpmreleasetoolkit.gemspec
Labels: enhancement
