Repository wordpress-mobile/release-toolkit, pull requests merged in 2024-10, with the labels that each got.

#606 Update Xcode CI image, CI Toolkit, and Ruby dependencies
  .buildkite/pipeline.yml
  Gemfile.lock
Labels: tooling

#607 Fix PR validity check in `create_release_backmerge_pr`
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/create_release_backmerge_pull_request_action.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/git_helper.rb
  spec/create_release_backmerge_pull_request_spec.rb
  spec/git_helper_spec.rb
Labels: bug

#609 Release 12.3.0 into trunk
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases
