Repository wordpress-mobile/release-toolkit, pull requests merged in 2025-03, with the labels that each got.

#636 Add `upload_build_to_apps_cdn` action
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/upload_build_to_apps_cdn.rb
  spec/upload_build_to_apps_cdn_spec.rb
Labels: enhancement

#640 Release 13.0.0
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases

#638 Introduce monkey-patch to auto-insert collapsible sections in Buildkite logs
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/helper/buildkite_aware_log_groups.rb
Labels: enhancement

#642 Fix `prototype_build_details_comment` action when used outside FAD context
  CHANGELOG.md
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/prototype_build_details_comment_action.rb
  spec/prototype_build_details_comment_action_spec.rb
Labels: bug

#641 Add `api_url` parameter to `create_release_backmerge_pull_request`
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/actions/common/create_release_backmerge_pull_request_action.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_localize_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_adc_app_sizes_helper.rb
  lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_strings_file_validation_helper.rb
  spec/create_release_backmerge_pull_request_spec.rb
Labels: enhancement

#643 Release `13.1.0`
  CHANGELOG.md
  Gemfile.lock
  lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Labels: Releases
